<a href="https://colab.research.google.com/github/pragnakulkarni/Pandas/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/main/pandas/tests/io/data/csv/tips.csv

In [17]:
d = {'a' : 1, 'b' : 2, 'c' : 3}
series1 = pd.Series(d)
print(series1)
series2 = pd.Series(d, index = ['a', 'b'])
print(series2)
series3 = pd.Series(d,index = ['a','x'],name = 'data series')
print(series3)
print('printing using the dictionary key: ',series1['b'])

a    1
b    2
c    3
dtype: int64
a    1
b    2
dtype: int64
a    1.0
x    NaN
Name: data series, dtype: float64
printing using the dictionary key:  2

In [18]:
l = [1,2,3]
ser1 = pd.Series(l)
print(ser1)
ser2 = pd.Series(l,index = ['x','y','z'],name = 'list data series')
print(ser2)

0    1
1    2
2    3
dtype: int64
x    1
y    2
z    3
Name: list data series, dtype: int64

In [27]:
l1 = [1,2]
ser = pd.Series(l1, copy = False)
print('series before update: ')
print(ser)
print('-------------')
ser[0] = 20
print('original list',l1)
print('-------------')
print('series after update: ')
print(ser)
print('in case of python objects, the original data will not be changed independent of the copy parameter')

series before update:
0    1
1    2
dtype: int64
-------------
original list [1, 2]
-------------
series after update:
0    20
1     2
dtype: int64
in case of python objects, the original data will not be changed independent of the copy parameter

In [29]:
import numpy as np
l2 = np.array([1,2])
print('original list',l1)
print('-------------')
ser3 = pd.Series(l2, copy = False)
print('series before update: ')
print(ser3)
print('-------------')
ser3[0] = 20
print('series after update: ')
print(ser)
print('in case of numpy arrays, the original data will  be changed if the copy parameter is set to False or the origibal data will be same in the numpy array')

original list [1, 2]
-------------
series before update:
0    1
1    2
dtype: int64
-------------
series after update:
0    20
1     2
dtype: int64
in case of numpy arrays, the original data will  be changed if the copy parameter is set to False or the origibal data will be same in the numpy array

In [9]:
#dataframes using dictionaries
dict = {'numbers' : [1,2,3], 'letters' : ['a','b','c']}
dic_dif = pd.DataFrame(dict)
print(dic_dif)
print('------------------------')
dic_dif = pd.DataFrame.from_dict(dict)
print(dic_dif)
print('------------------------')
dic_df = pd.DataFrame.from_dict(dict, orient = 'index')
print(dic_df)
print('------------------------')
#if only orient parameter is mentioned the key value is the index and the column titles are set to default
dic_df = pd.DataFrame.from_dict(dict, orient = 'index', columns = ['A','B','C'])
print(dic_df)

print('this orient parameter works only with the from_dict function')

   numbers letters
0        1       a
1        2       b
2        3       c
------------------------
   numbers letters
0        1       a
1        2       b
2        3       c
------------------------
         0  1  2
numbers  1  2  3
letters  a  b  c
------------------------
         A  B  C
numbers  1  2  3
letters  a  b  c
this orient parameter works only with the from_dict function

In [28]:
#data frames for csv files
# it is done using the read_csv() function
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/main/pandas/tests/io/data/csv/tips.csv'
csv_df = pd.read_csv(url)
print(csv_df)
print('---------------------------------------------------------------')
csv_df = pd.read_csv(url, index_col = ['total_bill'])
print(csv_df)
print('---------------------------------------------------------------')
csv_df = pd.read_csv(url, sep = '.')
print(csv_df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]
---------------------------------------------------------------
             tip     sex smoker   day    time  size
total_bill
16.99       1.01  Female     No   Sun  Dinner     2
10.34       1.66    Male     No   Sun  Dinner     3
21.01       3.50    Male     No   Sun  Dinner     3
23.68       3.31    Male     No   Sun  Dinner     2
24.59       3.61  Female     No   Sun  Dinner     4
...          ...     ...    ...   ...     ...   ...
29.03       5.92    Male     No   Sat  Dinner     3
27.18       2.00  Female    Yes   Sat  Dinner     2
22.67       2.00    Male    Yes   Sat  Dinner     2
17.82       1.75    Male     No   Sat  Dinner     2
18.78       3.00  Female     No  Thur  Dinner     2

[244 rows x 6 columns]
---------------------------------------------------------------
        total_bill,tip,sex,smoker,day,time,size
16 99,1               01,Female,No,Sun,Dinner,2
10 34,1                 66,Male,No,Sun,Dinner,3
21 01,3                  5,Male,No,Sun,Dinner,3
23 68,3                 31,Male,No,Sun,Dinner,2
24 59,3               61,Female,No,Sun,Dinner,4
...                                         ...
29 03,5                 92,Male,No,Sat,Dinner,3
27 18,2               0,Female,Yes,Sat,Dinner,2
22 67,2                 0,Male,Yes,Sat,Dinner,2
17 82,1                 75,Male,No,Sat,Dinner,2
18 78,3               0,Female,No,Thur,Dinner,2

[244 rows x 1 columns]

In [35]:
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/main/pandas/tests/io/data/csv/tips.csv'
csv_df = pd.read_csv(url)
print(csv_df.head())
print('-------------------------------------------------------------')
print(csv_df.head(6))
print('-------------------------------------------------------------')
print(csv_df.tail())
print('-------------------------------------------------------------')
print(csv_df.tail(8))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
-------------------------------------------------------------
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
-------------------------------------------------------------
     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2
-------------------------------------------------------------
     total_bill   tip     sex smoker   day    time  size
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [38]:
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/main/pandas/tests/io/data/csv/tips.csv'
csv_df = pd.read_csv(url, index_col = ['total_bill'])
print('before reset')
print(csv_df)
print('-------------------------------------------------------------')
# to reset the index to default we can either re-assign it to the variable or can use the inplace parameter in reset_index function
csv_df.reset_index(inplace = True)
print('after reset')
print(csv_df)

before reset
             tip     sex smoker   day    time  size
total_bill
16.99       1.01  Female     No   Sun  Dinner     2
10.34       1.66    Male     No   Sun  Dinner     3
21.01       3.50    Male     No   Sun  Dinner     3
23.68       3.31    Male     No   Sun  Dinner     2
24.59       3.61  Female     No   Sun  Dinner     4
...          ...     ...    ...   ...     ...   ...
29.03       5.92    Male     No   Sat  Dinner     3
27.18       2.00  Female    Yes   Sat  Dinner     2
22.67       2.00    Male    Yes   Sat  Dinner     2
17.82       1.75    Male     No   Sat  Dinner     2
18.78       3.00  Female     No  Thur  Dinner     2

[244 rows x 6 columns]
-------------------------------------------------------------
after reset
     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [60]:
# csv_df.reset_index(inplace = True)
# DataFrame.index gives the indexes of the data frame
print(csv_df.index)
# DataFrame.columns gives the columns of the data frame
print(csv_df.columns)
print('----------------------------------------------------')
# csv_df.drop(columns = ['level_0','index'], inplace = True)

# To change the index of an existing DataFrame, we use the DataFrame.set_index() function.
csv_df.set_index(['total_bill','tip'], inplace = True)
print(csv_df.index)
print(csv_df.columns)
print('----------------------------------------------------')

RangeIndex(start=0, stop=244, step=1)
Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')
----------------------------------------------------
MultiIndex([(16.99, 1.01),
            (10.34, 1.66),
            (21.01,  3.5),
            (23.68, 3.31),
            (24.59, 3.61),
            (25.29, 4.71),
            ( 8.77,  2.0),
            (26.88, 3.12),
            (15.04, 1.96),
            (14.78, 3.23),
            ...
            (15.53,  3.0),
            (10.07, 1.25),
            ( 12.6,  1.0),
            (32.83, 1.17),
            (35.83, 4.67),
            (29.03, 5.92),
            (27.18,  2.0),
            (22.67,  2.0),
            (17.82, 1.75),
            (18.78,  3.0)],
           names=['total_bill', 'tip'], length=244)
Index(['sex', 'smoker', 'day', 'time', 'size'], dtype='object')
----------------------------------------------------

In [70]:
# describe() shows a quick statistic summary of your data:
#  describe function only applicable for the columns and not for the indexes
print(csv_df.describe())
print('---------------------------')
# csv_df.size.describe()
csv_df

             size
count  244.000000
mean     2.569672
std      0.951100
min      1.000000
25%      2.000000
50%      2.000000
75%      3.000000
max      6.000000
---------------------------

                    sex smoker   day    time  size
total_bill tip
16.99      1.01  Female     No   Sun  Dinner     2
10.34      1.66    Male     No   Sun  Dinner     3
21.01      3.50    Male     No   Sun  Dinner     3
23.68      3.31    Male     No   Sun  Dinner     2
24.59      3.61  Female     No   Sun  Dinner     4
...                 ...    ...   ...     ...   ...
29.03      5.92    Male     No   Sat  Dinner     3
27.18      2.00  Female    Yes   Sat  Dinner     2
22.67      2.00    Male    Yes   Sat  Dinner     2
17.82      1.75    Male     No   Sat  Dinner     2
18.78      3.00  Female     No  Thur  Dinner     2

[244 rows x 5 columns]